routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
 
//Route::get('/', 'HomeController@index')->name('home');

Route::group( ['middleware' => ['auth']], function() {
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
    Route::resource('comments', 'CommentController');
  
    Route::resource('profiles', 'ProfileController');
    Route::get('/profile/photo/{user}', 'ProfileController@destroy_photo')->name('destroy.profilePhoto');
    Route::get('/user/perms/{user}', 'UserController@getUserPermissions')->name('users.permissions');

});

// Administration
Route::group( ['middleware' => ['auth', 'role:admin']], function() {
  Route::resource('roles', 'RoleController');
  Route::resource('permissions', 'PermissionController');
});

Route::get('/', function () {
    return view("bootstrap");
});



Route::get('/api/users', 'UserController@index')->name('users.index.api');

Route::get("/api/animals", function() {
    return response()->json([['name' => 'dog'], ['name' => 'cat'], ['name' => 'elephant'], ['name' => 'elk'], ['name' => 'spider']]);
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable {

    use Notifiable,
        HasRoles;
    
    protected $guard_name = 'web'; 
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts() {
        return $this->hasMany(Post::class);
    }
    
    
    public function profile() {
        return $this->HasOne(Profile::class);
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;
use App\User;
use App\Permission;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller {

    public function index(Request $request) {
        $result = User::latest()->with('profile')->paginate();
        $usersPhotos = array();
        foreach ($result as $item) {

            if ($item->profile['user_photo'] != null) {
                // configure with favored image driver (gd by default)
                Image::configure(array('driver' => 'imagick'));

                // and you are ready to go ...
                $usersPhotos[$item->id] = $item->profile['user_photo'];
            }
        }
        
        // Api queries.
        if($request->is('api/*')){
            return response()->json([$result, 'status' => 200]);
        }


        return view('user.index', compact('result', 'usersPhotos'));
    }

    public function create() {
        $roles = Role::pluck('name', 'id');
        return view('user.new', compact('roles'));
    }

    public function store(Request $request) {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'roles' => 'required|min:1'
        ]);
        

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ($user = User::create($request->except('roles', 'permissions'))) {
            
            // Assign role by default.
            $user->assignRole('user');
            $user->save();
          //  $this->syncPermissions($request, $user);
            flash('User has been created.');
        } else {
            flash()->error('Unable to create user.');
        }

        return redirect()->route('users.index');
    }

    public function edit($user_id) {
        
        $user = Auth::user();
 
        // Only users with this permission can edit no owned user profiles.
        if(!$user->hasPermissionTo('edit_all users')){
            if($user->id != $user_id){
                flash()->success('You have not permission papi!.');
                return redirect('profiles/' . $user->id . '/edit');
            }
        }
         
       
        $roles = Role::pluck('name', 'id');
        $permissions = Permission::all('name', 'id');

        return view('user.edit', compact('user', 'roles', 'permissions'));
    }

    public function update(Request $request, $id) {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,
            'roles' => 'required|min:1'
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'))->save();

        // check for password change
        if ($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        $roles = $request['roles'];
        if (isset($roles)) {        
            $user->roles()->sync($roles);          
        }        
        else {
            $user->roles()->detach();
        }
       
      
        flash()->success('User has been updated.');
        return redirect('profiles/' . $user->id . '/edit');
    }

    public function destroy($id) {
        if (Auth::user()->id == $id) {
            flash()->warning('Deletion of currently logged in user is not allowed :(')->important();
            return redirect()->back();
        }

        if (User::findOrFail($id)->delete()) {
            flash()->success('User has been deleted');
        } else {
            flash()->success('User not deleted');
        }

        return redirect()->back();
    }

    private function syncPermissions(Request $request, $user) {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if (!$user->hasAllRoles($roles)) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);
        return $user;
    }
    
    public function getUserPermissions(User $user){
       
        // All permissions which apply on the user (inherited and direct)
        $perms = $user->getAllPermissions();
        foreach ($perms as $perm){

            var_dump($perm->name);
        }
        
        $users = User::role('admin')->get(); 
        
        foreach ($users as $user){
            var_dump($user);
        }
    }

}

resources/views/user/_form.blade.php
<!-- Name Form Input -->
<div class="form-group @if ($errors->has('name')) has-error @endif">
    {!! Form::label('name', 'Name') !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Name']) !!}
    @if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
</div>

<!-- email Form Input -->
<div class="form-group @if ($errors->has('email')) has-error @endif">
    {!! Form::label('email', 'Email') !!}
    {!! Form::text('email', null, ['class' => 'form-control', 'placeholder' => 'Email']) !!}
    @if ($errors->has('email')) <p class="help-block">{{ $errors->first('email') }}</p> @endif
</div>

<!-- password Form Input -->
<div class="form-group @if ($errors->has('password')) has-error @endif">
    {!! Form::label('password', 'Password') !!}
    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']) !!}
    @if ($errors->has('password')) <p class="help-block">{{ $errors->first('password') }}</p> @endif
</div>

<!-- Roles Form Input -->
<div class="form-group @if ($errors->has('roles')) has-error @endif">
    {!! Form::label('roles[]', 'Roles') !!}
    {!! Form::select('roles[]', $roles, isset($user) ? $user->roles->pluck('id')->toArray() : null,  ['class' => 'form-control', 'multiple']) !!}
    @if ($errors->has('roles')) <p class="help-block">{{ $errors->first('roles') }}</p> @endif
</div>

<!-- Permissions -->
@if(isset($user))
    @include('shared._permissions', ['closed' => 'true', 'model' => $user ])
@endif

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit User ' . $user->name)

@section('content')
  <div class="navbar-header">

     <!-- Branding Image -->
<a class="navbar-brand" href="{{ route('profiles.edit', ['user_id' => $user->id]) }}">
   Edit Profile
</a>
</div>                  
    <div class="row">
        <div class="col-md-5">
            <h3>Edit {{ $user->name }}</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            <a href="{{ route('users.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Back</a>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-content">
                        {!! Form::model($user, ['method' => 'PUT', 'route' => ['users.update',  $user->id ] ]) !!}
                            @include('user._form')
                            <!-- Submit Form Button -->
                            {!! Form::submit('Save Changes', ['class' => 'btn btn-primary']) !!}
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index-table.blade.php
@extends('layouts.app')

@section('title', 'Users')

@section('content')
    <div class="row">
        <div class="col-md-5">
            <h3 class="modal-title">{{ $result->total() }} {{ str_plural('User', $result->count()) }} </h3>
        </div>
        <div class="col-md-7 page-action text-right">
            @can('add_users')
                <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm"> <i class="glyphicon glyphicon-plus-sign"></i> Create</a>
            @endcan
        </div>
    </div>

    <div class="result-set">
        <table class="table table-bordered table-striped table-hover" id="data-table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Created At</th>
                <th>Photo</th>
                @can('edit_users', 'delete_users')
                <th class="text-center">Actions</th>
                @endcan
            </tr>
            </thead>
            <tbody>
            @foreach($result as $item)
                <tr>
                    <td>{{ $item->id }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->email }}</td>
                    <td>{{ $item->roles->implode('name', ', ') }}</td>
                    <td>{{ $item->created_at->toFormattedDateString() }}</td>
                    <td>
                    @if (isset($usersPhotos[$item->id]))                                                 
                    <?php $urlPhoto = asset('storage/user_photo/' . $usersPhotos[$item->id]); ?>
                            <img src="<?php echo $urlPhoto; ?>" />
                        @endif
                    </td>
                    @can('edit_users')
                    <td class="text-center">
                        @include('shared._actions', [
                            'entity' => 'users',
                            'id' => $item->id
                        ])
                    </td>
                    @endcan
                </tr>
            @endforeach
            </tbody>
        </table>

        <div class="text-center">
            {{ $result->links() }}
        </div>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'Users')

@section('content')
    <div class="row">
        <div class="col-md-5">
            <h3 class="modal-title">{{ $result->total() }} {{ str_plural('User', $result->count()) }} </h3>
        </div>
        <div class="col-md-7 page-action text-right">
            @can('add_users')
                <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm"> <i class="glyphicon glyphicon-plus-sign"></i> Create</a>
            @endcan
        </div>
    </div>

    <div class="result-set">
       
            <tbody>
            <div class="container-fluid">
                 <div class="row">
                    @foreach($result as $item)
                        <div class="col-md-3 pull-left">
                            <p>{{ $item->id }}</p>
                            
                            <p>
                            @if (isset($usersPhotos[$item->id]) && $usersPhotos[$item->id] != null)                                                 
                                <?php $urlPhoto = asset('storage/user_photo/' . $usersPhotos[$item->id]); ?>                             
                            @else
                                <?php $urlPhoto = asset('storage/user_photo/demo.png'); ?>
                            @endif                                               
                            <img src="<?php echo $urlPhoto; ?>" />
                            </p>
                            
                            <p  style="display: inline">       
                            @include('shared._actions', [
                                    'entity' => 'users',
                                    'id' => $item->id
                                ]) 
                            </p>
                            
                            <p>
                                {{ $item->name }} 
                            </p>
                            
                            <p>{{ $item->email }}</p>
                            
                            <p>{{ $item->roles->implode('name', ', ') }}</p>
                            
                            <p>{{ $item->created_at->toFormattedDateString() }}</p>


                        </div>

                    @endforeach
                 </div>
             </div>    
            </tbody>
       

        <div class="text-center">
            {{ $result->links() }}
        </div>
    </div>

@endsection

resources/views/user/new.blade.php
@extends('layouts.app')

@section('title', 'Create')

@section('content')

    <div class="row">
        <div class="col-md-5">
            <h3>Create</h3>
        </div>
        <div class="col-md-7 page-action text-right">
            <a href="{{ route('users.index') }}" class="btn btn-default btn-sm"> <i class="fa fa-arrow-left"></i> Back</a>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {!! Form::open(['route' => ['users.store'] ]) !!}
                @include('user._form')
                <!-- Submit Form Button -->
                {!! Form::submit('Create', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection